### ISSUE TITLE
Need Hero Image please 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Pennsylvania-Policy-Database-Project#4]
Hey Zac, when you have a moment can you give this center a hero? Below is the image they submitted (which is in the media library) but it's not going to work). Thanks! 

https://github.com/TULiberalArts/Pennsylvania-Policy-Database-Project/blob/master/media/papolicyhero.jpg?raw=true

**Comment by ZMcGroarty** [comment]
Lets try this, its not great but we're super limited on options for this.

![padb-min](https://user-images.githubusercontent.com/15017242/46292154-30230800-c55e-11e8-95b4-692b3839d879.png)

**Comment by CVE82** [comment]
Awesome thank you, trying now!
