### ISSUE TITLE
Affiliated feed is giving a syntax error

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Pennsylvania-Policy-Database-Project#5]
The affiliated profiles include on the Researchers page is breaking and giving that syntax error message.

**Comment by CVE82** [comment]
I have removed the affiliated include, changed the Researcher page layout back to tla_page and moved the original content back into the page until we can get the faculty to feed in from Drupal and the include to work. Thanks!

**Comment by tu-chill** [comment]
<img width="1068" alt="screen shot 2018-10-02 at 4 14 22 pm" src="https://user-images.githubusercontent.com/12816361/46374245-3ef0e400-c65e-11e8-8abd-db389202077a.png">


I have it working but the include seems unfinished <Need Content>
